/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import utilidades.Util;

/**
 *Clase principal del proyecto que contiene el menú principal
 * @author coder
 */
public class MainInterface extends javax.swing.JFrame {

    Util utilidades;
    ArrayList<Jugador> jugadores;
    RegistrarJugador registrarJugador;

    /**
     * Constructor del menú principal que inicializa los valores de la clase.
     */
    public MainInterface() {
        utilidades = new Util();
        setResizable(false);
        this.setBounds(450, 250, 0, 0);
        initComponents();
        jugadores = new ArrayList<>();
    }
    
    /**
     * Metodo que sobrecarga el constructor para recibir jugadores de otras clases.
     * @param juga ArrayList de Jugadores
     */
    public MainInterface(ArrayList<Jugador> juga) {
        utilidades = new Util();
        jugadores = new ArrayList<>();
        setResizable(false);
        this.setBounds(450, 250, 0, 0);
        this.jugadores = juga;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONCÉNTRESE");

        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Registrar Jugador");
        jButton2.setPreferredSize(new java.awt.Dimension(71, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ver Resultados");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Créditos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/back.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButton3))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButton4))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton1))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // evento de cuadro de diálogo que se presenta antes de iniciar el juego.
        try {
            String answer = JOptionPane.showInputDialog(this, "Ingresa tu código de jugador", "¡Casi listos para iniciar!", JOptionPane.INFORMATION_MESSAGE);
            if (!answer.trim().isEmpty()) { // si no esta vacia la caja de texto
                if (utilidades.buscarJugador(answer, jugadores) != -1) { // buscar jugador por su código.
                    this.dispose(); //cerrar interfaz actual.
                    Juego juego = new Juego(jugadores, jugadores.get(utilidades.buscarJugador(answer, jugadores))); // Creando nuevo juego.
                    juego.setVisible(true); // haciendo visible la interfaz de juego.
                } else {
                    // mensaje de excepción cuando no encuentra al usuario en arraylist.
                    JOptionPane.showMessageDialog(this, "Lo sentimos, no te encontramos entre los usuarios registrados.\n¡Registrate! te llevará menos de un minuto", "Error al ingresar", JOptionPane.ERROR_MESSAGE);
                }

            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Evento del boton registrar jugadores
        this.dispose(); //cierra la interfaz actual
        if (jugadores.isEmpty()) { //sino hay jugadores instancia normal
            registrarJugador = new RegistrarJugador();
            registrarJugador.setVisible(true);
        } else {
            registrarJugador = new RegistrarJugador(jugadores); // si hay jugadores los envía a la interfaz de registrar jugadores.
            registrarJugador.setVisible(true);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Creditos creditos = new Creditos(); // evento del boton creditos
        creditos.setLocationRelativeTo(this);
        creditos.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        Resultados resultados = new Resultados(jugadores); //evento del boton resultados que carga la lista con posiciones de jugadores.
        resultados.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
